import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { inter } from '@/components/fonts';
import SideNav from '@/components/sidenav'


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-screen border-2 border-black">
          <div className="border-2 border-black">
            <SideNav />
          </div>
          <div className="flex flex-grow w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
